--- drone/docker/Dockerfile.server.linux.amd64	2021-07-18 10:08:13.000000000 +0800
+++ drone/docker/Dockerfile-copy.server.linux	2021-07-18 10:21:45.000000000 +0800
@@ -17,8 +17,9 @@
 ENV DRONE_RUNNER_ARCH=amd64
 ENV DRONE_SERVER_PORT=:80
 ENV DRONE_SERVER_HOST=localhost
-ENV DRONE_DATADOG_ENABLED=true
+ENV DRONE_DATADOG_ENABLED=false
 ENV DRONE_DATADOG_ENDPOINT=https://stats.drone.ci/api/v1/series
+ENV DRONE_AGENTS_DISABLED=true
 
 COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
 
